use_frameworks!

platform :ios, '9.0'

target 'CardIOSDKBridge_Example' do
  pod 'CardIOSDKBridge', :path => '../'

  target 'CardIOSDKBridge_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
